name: Retrieve API Key from Vault

on:
  push:
    branches:
      - master

jobs:
  get-api-key:
    runs-on: ubuntu-latest


    steps:
        - name: Import Secrets
          id: import-secrets
          uses: hashicorp/vault-action@v2
          with:
            url: ${{ secrets.VAULT_ADDR }}
            token: ${{ secrets.VAULT_TOKEN }}
            secrets: |
                secret/data/ci api-key | API_KEY;
                
        - name: Step following Import Secrets
          run:  |
            API_KEY = "${{ env.API_KEY }}"
            docker run -t owasp/zap2docker-stable zap-api-scan.py  -t "https://api.openweathermap.org/data/2.5/weather?q=CityName&appid=${{ env.API_KEY }}" -f openapi -r zap_report.html

