name: Retrieve API Key from Vault

on:
  push:
    branches:
      - master

jobs:
  get-api-key:
    runs-on: ubuntu-latest


    steps:
        - name: Import Secrets
          id: import-secrets
          uses: hashicorp/vault-action@v2
          with:
            url: ${{ secrets.VAULT_ADDR}}
            caCertificate: ${{ secrets.CA_CERT_PATH }}
            token: ${{ secrets.VAULT_TOKEN }}
            secrets: |
                secret/data/capstone api-key | API_KEY;
