name: OWASP ZAP Quick Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull OWASP ZAP Docker Image
        run: docker pull owasp/zap2docker-stable

      - name: Run OWASP ZAP Quick Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable \
          zap-baseline.py \
          -t https://www.example.com -g gen.conf -r testreport.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
