name: ZAP Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install OWASP ZAP
        run: |
          sudo add-apt-repository ppa:owasp-zap/ppa
          sudo apt-get update
          sudo apt-get install zaproxy

      - name: Run ZAP scan
        run: |
          zap.sh -cmd -quickurl http://juiceshop.herokuapp.com -quickout zap_report.html -quickreport html
